spring.application.name=wagetrack
spring.datasource.url=jdbc:mysql://localhost:3306/wage_track
spring.datasource.username=root
spring.datasource.password=Gokul@2667
spring.jpa.hibernate.ddl-auto=update
